version: '3.7'
services:
  adminer:
    image: adminer
    ports:
      - '8082:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db-dev
      ADMINER_DEFAULT_USERNAME: mostafa
      ADMINER_DEFAULT_PASSWORD: 123456789
      ADMINER_DEFAULT_DATABASE: library

  db-dev:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: library
      MYSQL_USER: mostafa
      MYSQL_PASSWORD: 123456789

  lib:
    build:
      context: .
      dockerfile: Dockerfile
    image: lib:latest
    env_file:
      - ./src/.env
    ports:
      - '8000:8000'
    depends_on:
      - db-dev
